Repository openshift/kube-compare, pull requests merged in 2024-06, with the labels that each got.

#24 Update OWNERS
  OWNERS
Labels: lgtm, ok-to-test, approved

#26 Add regex match to tests to get around OS depenent path in errors.
  pkg/compare/compare_test.go
Labels: lgtm, ok-to-test, approved

#23 fix issues from golangci-lint
  addon-tools/report-creator/report/create_test.go
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/compare/httpfs.go
  pkg/compare/parsing.go
Labels: lgtm, ok-to-test, approved

#33 Add golangci-lint to makefile
  Makefile
  hack/golangci-lint.sh
Labels: lgtm, approved

#34 Remove jq from golangci-lint script and add more linters
  .golangci.yml
  hack/golangci-lint.sh
Labels: lgtm, approved

#35 Fix linting extended linters
  .golangci.yml
  addon-tools/report-creator/junit/junit.go
  addon-tools/report-creator/report/create.go
  addon-tools/report-creator/report/create_test.go
  addon-tools/report-creator/report/testdata/Creation Of Missing CRs And Unmatched CRs And Diff Tests Suites When No Diffs Creation Of Missing CRs And Unmatched CRs And Diff Tests Suites When No Diffs.golden
  addon-tools/report-creator/report/testdata/Diff Test Suite Creation When There Are Diffs Diff Test Suite Creation When There Are Diffs.golden
  addon-tools/report-creator/report/testdata/Missing CRs test suite creation when CRS are Missing Missing CRs test suite creation when CRS are Missing.golden
  addon-tools/report-creator/report/testdata/Unmatched CRs Test Suite When CRs Are Unmatched Unmatched CRs Test Suite When CRs Are Unmatched.golden
  cmd/kubectl-cluster_compare.go
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/compare/correlator.go
  pkg/compare/httpfs.go
  pkg/compare/parsing.go
  pkg/compare/testdata/TemplateHasNoKind/liveerr.golden
  pkg/compare/testdata/TemplateIsntYAMLAfterExecutionWithEmptyMap/localerr.golden
  pkg/compare/testdata/TestLocalResourceFileDoesntexist/localerr.golden
  pkg/groups/groups.go
Labels: lgtm, approved

#38 Fix golangci lint timeout config
  .golangci.yml
Labels: lgtm, approved

#39 Remove trailing whitespace from summary template and error-code
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/compare/testdata/JSONOutput/localerr.golden
  pkg/compare/testdata/ManualCorrelationMatchesArePrioritizedOverGroupCorrelation/liveerr.golden
  pkg/compare/testdata/ManualCorrelationMatchesArePrioritizedOverGroupCorrelation/liveout.golden
  pkg/compare/testdata/ManualCorrelationMatchesArePrioritizedOverGroupCorrelation/localerr.golden
  pkg/compare/testdata/ManualCorrelationMatchesArePrioritizedOverGroupCorrelation/localout.golden
  pkg/compare/testdata/NoInput/localerr.golden
  pkg/compare/testdata/OnlyRequiredResourcesOfRequiredComponentAreReportedMissing(OptionalResourcesNotReported)/liveerr.golden
  pkg/compare/testdata/OnlyRequiredResourcesOfRequiredComponentAreReportedMissing(OptionalResourcesNotReported)/liveout.golden
  pkg/compare/testdata/OnlyRequiredResourcesOfRequiredComponentAreReportedMissing(OptionalResourcesNotReported)/localerr.golden
  pkg/compare/testdata/OnlyRequiredResourcesOfRequiredComponentAreReportedMissing(OptionalResourcesNotReported)/localout.golden
  pkg/compare/testdata/OnlyResourcesThatWereNotMatchedBecauseMultipleMatchesAppearInSummary/localerr.golden
  pkg/compare/testdata/OnlyResourcesThatWereNotMatchedBecauseMultipleMatchesAppearInSummary/localout.golden
  pkg/compare/testdata/RefTemplateInSubDirNotReportedMissing/liveerr.golden
  pkg/compare/testdata/RefTemplateInSubDirNotReportedMissing/localerr.golden
  pkg/compare/testdata/RefTemplateInSubDirWorksWithManualCorrelation/liveerr.golden
  pkg/compare/testdata/RefTemplateInSubDirWorksWithManualCorrelation/localerr.golden
  pkg/compare/testdata/RefWithTemplateFunctionsRendersAsExpected/liveerr.golden
  pkg/compare/testdata/RefWithTemplateFunctionsRendersAsExpected/localerr.golden
  pkg/compare/testdata/ReferenceConfigFileIsntValidYAML/localerr.golden
  pkg/compare/testdata/ReferenceContainsFunctionTemplatesThatDontParse/localerr.golden
  pkg/compare/testdata/ReferenceContainsTemplatesThatDontExist/localerr.golden
  pkg/compare/testdata/ReferenceContainsTemplatesThatDontParse/localerr.golden
  pkg/compare/testdata/ReferenceDirectoryDoesntExist/localerr.golden
  pkg/compare/testdata/RequiredResourcesOfOptionalComponentAreReportedMissingIfAtLeastOneOfResourcesInGroupIsIncluded/liveerr.golden
  pkg/compare/testdata/RequiredResourcesOfOptionalComponentAreReportedMissingIfAtLeastOneOfResourcesInGroupIsIncluded/liveout.golden
  pkg/compare/testdata/RequiredResourcesOfOptionalComponentAreReportedMissingIfAtLeastOneOfResourcesInGroupIsIncluded/localerr.golden
  pkg/compare/testdata/RequiredResourcesOfOptionalComponentAreReportedMissingIfAtLeastOneOfResourcesInGroupIsIncluded/localout.golden
  pkg/compare/testdata/TemplateHasNoKind/liveerr.golden
  pkg/compare/testdata/TemplateIsntYAMLAfterExecutionWithEmptyMap/localerr.golden
  pkg/compare/testdata/TemplatesContainKindThatIsNotRecognizableInLiveCluster/liveerr.golden
  pkg/compare/testdata/TemplatesContainKindThatIsNotRecognizableInLiveCluster/liveout.golden
  pkg/compare/testdata/TestLocalResourceFileDoesntexist/localerr.golden
  pkg/compare/testdata/TwoTemplatesWithSameKindNamespace/localerr.golden
  pkg/compare/testdata/TwoTemplatesWithSameKindNamespace/localout.golden
  pkg/compare/testdata/TwoTemplatesWithSameapiVersionKindNameNamespace/localerr.golden
  pkg/compare/testdata/TwoTemplatesWithSameapiVersionKindNameNamespace/localout.golden
  pkg/compare/testdata/UserConfigIsntCorrectYAML/localerr.golden
  pkg/compare/testdata/UserConfigManualCorrelationContainsTemplateThatDoesntExist/localerr.golden
  pkg/compare/testdata/WhenUsingDiffAllFlag-AllUnmatchedResourcesAppearInSummary/localerr.golden
  pkg/compare/testdata/WhenUsingDiffAllFlag-AllUnmatchedResourcesAppearInSummary/localout.golden
  pkg/compare/testdata/YAMLOutput/localerr.golden
Labels: lgtm, approved

#43 CNF-12627: Change kubectl prefix in help message
  pkg/compare/compare.go
Labels: lgtm, jira/valid-reference, approved

#37 Merge reference info live before diff to get more relevent diffs
  .golangci.yml
  README.md
  docs/reference-config-guide.md
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/compare/correlator.go
  pkg/compare/parsing.go
  pkg/compare/testdata/AllRequiredTemplatesExistAndThereAreNoDiffs/reference/metadata.yaml
  pkg/compare/testdata/CheckIgnoreUnspecifiedFieldsConfig/localerr.golden
  pkg/compare/testdata/CheckIgnoreUnspecifiedFieldsConfig/localout.golden
  pkg/compare/testdata/CheckIgnoreUnspecifiedFieldsConfig/reference/metadata.yaml
  pkg/compare/testdata/CheckIgnoreUnspecifiedFieldsConfig/reference/namespace.yaml
  pkg/compare/testdata/CheckIgnoreUnspecifiedFieldsConfig/resources/ns.yaml
  pkg/compare/testdata/CheckMergingDoesNotOverwriteTemplateConfig/localerr.golden
  pkg/compare/testdata/CheckMergingDoesNotOverwriteTemplateConfig/localout.golden
  pkg/compare/testdata/CheckMergingDoesNotOverwriteTemplateConfig/reference/metadata.yaml
  pkg/compare/testdata/CheckMergingDoesNotOverwriteTemplateConfig/reference/namespace.yaml
  pkg/compare/testdata/CheckMergingDoesNotOverwriteTemplateConfig/resources/ns.yaml
  pkg/compare/testdata/DiffinCustomOmittedFieldsIsntShown/reference/metadata.yaml
  pkg/compare/testdata/JSONOutput/reference/metadata.yaml
  pkg/compare/testdata/ManualCorrelationMatchesArePrioritizedOverGroupCorrelation/reference/metadata.yaml
  pkg/compare/testdata/OnlyRequiredResourcesOfRequiredComponentAreReportedMissing(OptionalResourcesNotReported)/reference/metadata.yaml
  pkg/compare/testdata/OnlyResourcesThatWereNotMatchedBecauseMultipleMatchesAppearInSummary/reference/metadata.yaml
  pkg/compare/testdata/RefTemplateInSubDirNotReportedMissing/reference/metadata.yaml
  pkg/compare/testdata/RefTemplateInSubDirWorksWithManualCorrelation/reference/metadata.yaml
  pkg/compare/testdata/RefWithTemplateFunctionsRendersAsExpected/reference/metadata.yaml
  pkg/compare/testdata/ReferenceContainsFunctionTemplatesThatDontParse/reference/metadata.yaml
  pkg/compare/testdata/ReferenceContainsTemplatesThatDontExist/reference/metadata.yaml
  pkg/compare/testdata/ReferenceContainsTemplatesThatDontParse/reference/metadata.yaml
  pkg/compare/testdata/RequiredResourcesOfOptionalComponentAreNotReportedMissing/reference/metadata.yaml
  pkg/compare/testdata/RequiredResourcesOfOptionalComponentAreReportedMissingIfAtLeastOneOfResourcesInGroupIsIncluded/reference/metadata.yaml
  pkg/compare/testdata/TemplateHasNoKind/reference/metadata.yaml
  pkg/compare/testdata/TemplateIsntYAMLAfterExecutionWithEmptyMap/reference/metadata.yaml
  pkg/compare/testdata/TemplatesContainKindThatIsNotRecognizableInLiveCluster/reference/metadata.yaml
  pkg/compare/testdata/TestLocalResourceFileDoesntexist/reference/metadata.yaml
  pkg/compare/testdata/TwoTemplatesWithSameKindNamespace/reference/metadata.yaml
  pkg/compare/testdata/TwoTemplatesWithSameapiVersionKindNameNamespace/reference/metadata.yaml
  pkg/compare/testdata/UserConfigDoesntExist/reference/metadata.yaml
  pkg/compare/testdata/UserConfigIsntCorrectYAML/reference/metadata.yaml
  pkg/compare/testdata/UserConfigManualCorrelationContainsTemplateThatDoesntExist/reference/metadata.yaml
  pkg/compare/testdata/WhenUsingDiffAllFlag-AllUnmatchedResourcesAppearInSummary/reference/metadata.yaml
  pkg/compare/testdata/YAMLOutput/reference/metadata.yaml
Labels: lgtm, approved
