Repository openshift/kube-compare, pull requests merged in 2024-11, with the labels that each got.

#131 Deal with the nondeterministic results from circular import detection
  pkg/compare/compare_test.go
  pkg/compare/testdata/ReferenceV2DiffinCustomOmittedFieldsIsntShown/local_circular_include_err.golden
  pkg/compare/testdata/ReferenceV2DiffinCustomOmittedFieldsIsntShown/local_circular_include_out.golden
Labels: lgtm, approved

#132 Escape values if refernce filenames contain '.'
  addon-tools/helm-convert/convert/convert.go
  addon-tools/helm-convert/convert/convert_test.go
  addon-tools/helm-convert/convert/testdata/OddFilenames/reference/config-map.yaml
  addon-tools/helm-convert/convert/testdata/OddFilenames/reference/crb.yml
  addon-tools/helm-convert/convert/testdata/OddFilenames/reference/deployment.dashboard.yaml
  addon-tools/helm-convert/convert/testdata/OddFilenames/reference/metadata.yaml
  addon-tools/helm-convert/convert/testdata/OddFilenames/reference/subdir/cr.yaml
  addon-tools/helm-convert/convert/testdata/OddFilenames/result/Chart.yaml
  addon-tools/helm-convert/convert/testdata/OddFilenames/result/templates/_helpers.tpl
  addon-tools/helm-convert/convert/testdata/OddFilenames/result/templates/config-map.yaml
  addon-tools/helm-convert/convert/testdata/OddFilenames/result/templates/crb.yml
  addon-tools/helm-convert/convert/testdata/OddFilenames/result/templates/deployment.dashboard.yaml
  addon-tools/helm-convert/convert/testdata/OddFilenames/result/templates/subdir/cr.yaml
  addon-tools/helm-convert/convert/testdata/OddFilenames/result/values.yaml
Labels: lgtm, approved

#129 CNF-15499: Allow references to supply per-template description text
  docs/reference-config-guide-v2.md
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/compare/output.go
  pkg/compare/parsing.go
  pkg/compare/referenceV1.go
  pkg/compare/referenceV2.go
  pkg/compare/testdata/Description/local_hidden_for_match_out.golden
  pkg/compare/testdata/Description/local_shown_for_diff_err.golden
  pkg/compare/testdata/Description/local_shown_for_diff_out.golden
  pkg/compare/testdata/Description/local_shown_for_missing_file_err.golden
  pkg/compare/testdata/Description/local_shown_for_missing_file_out.golden
  pkg/compare/testdata/Description/reference/cm-diff.yaml
  pkg/compare/testdata/Description/reference/cm-matches.yaml
  pkg/compare/testdata/Description/reference/cm-missing.yaml
  pkg/compare/testdata/Description/reference/metadata_hidden_for_match.yaml
  pkg/compare/testdata/Description/reference/metadata_shown_for_diff.yaml
  pkg/compare/testdata/Description/reference/metadata_shown_for_missing_file.yaml
  pkg/compare/testdata/Description/resources/configmap.yaml
  pkg/compare/testdata/DescriptionV1/local_hidden_for_match_out.golden
  pkg/compare/testdata/DescriptionV1/local_shown_for_diff_err.golden
  pkg/compare/testdata/DescriptionV1/local_shown_for_diff_out.golden
  pkg/compare/testdata/DescriptionV1/local_shown_for_missing_file_err.golden
  pkg/compare/testdata/DescriptionV1/local_shown_for_missing_file_out.golden
  pkg/compare/testdata/DescriptionV1/reference/cm-diff.yaml
  pkg/compare/testdata/DescriptionV1/reference/cm-matches.yaml
  pkg/compare/testdata/DescriptionV1/reference/cm-missing.yaml
  pkg/compare/testdata/DescriptionV1/reference/metadata_hidden_for_match.yaml
  pkg/compare/testdata/DescriptionV1/reference/metadata_shown_for_diff.yaml
  pkg/compare/testdata/DescriptionV1/reference/metadata_shown_for_missing_file.yaml
  pkg/compare/testdata/DescriptionV1/resources/configmap.yaml
Labels: lgtm, jira/valid-reference, approved

#135 Allow Metadata Description to be set at Part and Component levels
  docs/reference-config-guide-v2.md
  pkg/compare/compare_test.go
  pkg/compare/referenceV2.go
  pkg/compare/testdata/Description/local_component_shown_for_diff_err.golden
  pkg/compare/testdata/Description/local_component_shown_for_diff_out.golden
  pkg/compare/testdata/Description/local_part_shown_for_diff_err.golden
  pkg/compare/testdata/Description/local_part_shown_for_diff_out.golden
  pkg/compare/testdata/Description/local_precidence_c_t_shown_for_diff_err.golden
  pkg/compare/testdata/Description/local_precidence_c_t_shown_for_diff_out.golden
  pkg/compare/testdata/Description/local_precidence_p_c_shown_for_diff_err.golden
  pkg/compare/testdata/Description/local_precidence_p_c_shown_for_diff_out.golden
  pkg/compare/testdata/Description/local_precidence_p_c_t_shown_for_diff_err.golden
  pkg/compare/testdata/Description/local_precidence_p_c_t_shown_for_diff_out.golden
  pkg/compare/testdata/Description/local_precidence_p_t_shown_for_diff_err.golden
  pkg/compare/testdata/Description/local_precidence_p_t_shown_for_diff_out.golden
  pkg/compare/testdata/Description/reference/metadata_component_shown_for_diff.yaml
  pkg/compare/testdata/Description/reference/metadata_part_shown_for_diff.yaml
  pkg/compare/testdata/Description/reference/metadata_precidence_c_t_shown_for_diff.yaml
  pkg/compare/testdata/Description/reference/metadata_precidence_p_c_shown_for_diff.yaml
  pkg/compare/testdata/Description/reference/metadata_precidence_p_c_t_shown_for_diff.yaml
  pkg/compare/testdata/Description/reference/metadata_precidence_p_t_shown_for_diff.yaml
Labels: lgtm, approved

#124 main readme update
  README.md
Labels: lgtm, approved, kind/documentation

#137 compare of named capture group values in inline regex
  pkg/compare/capturegroupsInlineDiff.go
  pkg/compare/capturegroupsInlineDiff_test.go
  pkg/compare/regexInlineDiff.go
  pkg/compare/regexInlineDiff_test.go
  pkg/compare/testdata/ReferenceV2InlineRegex/localWithDiffInFirstLineout.golden
  pkg/compare/testdata/ReferenceV2InlineRegex/reference/cm-regex-with-diff-in-first-line.yaml
Labels: lgtm, approved

#142 OCPBUGS-44249: Introduce strictMatch correlation flag
  docs/user-guide.md
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/compare/correlator.go
  pkg/compare/parsing.go
  pkg/compare/testdata/StrictMatch/localerr.golden
  pkg/compare/testdata/StrictMatch/localout.golden
  pkg/compare/testdata/StrictMatch/localstrict_mode_onerr.golden
  pkg/compare/testdata/StrictMatch/localstrict_mode_onout.golden
  pkg/compare/testdata/StrictMatch/reference/deploymentDashboard.yaml
  pkg/compare/testdata/StrictMatch/reference/deploymentMetrics.yaml
  pkg/compare/testdata/StrictMatch/reference/metadata.yaml
  pkg/compare/testdata/StrictMatch/resources/d2.yaml
  pkg/compare/testdata/StrictMatch/resources/deploymentDashboard.yaml
  pkg/compare/testdata/StrictMatch/userconfig.yaml
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug

#143 Revert "Introduce strict-match correlation flag"
  docs/user-guide.md
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/compare/correlator.go
  pkg/compare/parsing.go
  pkg/compare/testdata/StrictMatch/localerr.golden
  pkg/compare/testdata/StrictMatch/localout.golden
  pkg/compare/testdata/StrictMatch/localstrict_mode_onerr.golden
  pkg/compare/testdata/StrictMatch/localstrict_mode_onout.golden
  pkg/compare/testdata/StrictMatch/reference/deploymentDashboard.yaml
  pkg/compare/testdata/StrictMatch/reference/deploymentMetrics.yaml
  pkg/compare/testdata/StrictMatch/reference/metadata.yaml
  pkg/compare/testdata/StrictMatch/resources/d2.yaml
  pkg/compare/testdata/StrictMatch/resources/deploymentDashboard.yaml
  pkg/compare/testdata/StrictMatch/userconfig.yaml
Labels: lgtm, approved
