Repository openshift/kube-compare, pull requests merged in 2024-09, with the labels that each got.

#97 Fix typo in docs
  README.md
  docs/reference-config-guide.md
Labels: lgtm, approved

#100 Modify go-releaser to build arm64 and not 386
  .goreleaser.yml
Labels: lgtm, approved

#102 CNF-14198: Add version to metadata but default to v1 if missing
  addon-tools/helm-convertor/convert/convert.go
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/compare/parsing.go
  pkg/compare/testdata/ReferenceConfigFileIsntValidYAML/localerr.golden
  pkg/compare/testdata/ReferenceHasInvalidVersion/localerr.golden
  pkg/compare/testdata/ReferenceHasInvalidVersion/localout.golden
  pkg/compare/testdata/ReferenceHasInvalidVersion/reference/cm.yaml
  pkg/compare/testdata/ReferenceHasInvalidVersion/reference/metadata.yaml
  pkg/compare/testdata/ReferenceHasInvalidVersion/resources/cm.yaml
  pkg/compare/testdata/ReferenceHasValidVersion/localout.golden
  pkg/compare/testdata/ReferenceHasValidVersion/reference/cm.yaml
  pkg/compare/testdata/ReferenceHasValidVersion/reference/metadata.yaml
  pkg/compare/testdata/ReferenceHasValidVersion/resources/cm.yaml
Labels: lgtm, jira/valid-reference, approved

#101 Added krew installation guide in install section
  README.md
Labels: lgtm, ok-to-test, approved

#106 Configure dependabot to do go vendoring
  .github/dependabot.yml
Labels: lgtm, approved

#99 Add downstream build documentation
  docs/downstream.md
Labels: lgtm, approved

#107 Revert "Configure dependabot to do go vendoring"
  .github/dependabot.yml
Labels: lgtm, approved

#109 Sync and vendor the workspace
  addon-tools/helm-convertor/go.mod
  addon-tools/helm-convertor/go.sum
  addon-tools/report-creator/go.mod
  addon-tools/report-creator/go.sum
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved

#110 Add dependencies label in Dependabot
  .github/dependabot.yml
Labels: lgtm, approved

#112 Add krew-bump.sh helper script for updating the krew index as part of release
  docs/release-guide.md
  hack/krew-bump.sh
Labels: lgtm, approved
